# Generated by Django 3.1.1 on 2020-09-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restFramework', '0002_remove_curso_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restFramework.pais'),
        ),
    ]
